# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vyper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/vyper.proto',
  package='iotex',
  syntax='proto3',
  serialized_options=b'Z\007./iotex',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11proto/vyper.proto\x12\x05iotex\"[\n\x0cVyperRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\"\n\x06source\x18\x02 \x01(\x0b\x32\x12.iotex.VyperSource\x12\x16\n\x0everifyBytecode\x18\x03 \x01(\t\"E\n\rVyperResponse\x12\x11\n\tcompileOK\x18\x01 \x01(\x08\x12\x10\n\x08verifyOK\x18\x02 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\",\n\x0bVyperSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2@\n\x05Vyper\x12\x37\n\x08\x63ompiler\x12\x13.iotex.VyperRequest\x1a\x14.iotex.VyperResponse\"\x00\x42\tZ\x07./iotexb\x06proto3'
)




_VYPERREQUEST = _descriptor.Descriptor(
  name='VyperRequest',
  full_name='iotex.VyperRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='iotex.VyperRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='iotex.VyperRequest.source', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verifyBytecode', full_name='iotex.VyperRequest.verifyBytecode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=119,
)


_VYPERRESPONSE = _descriptor.Descriptor(
  name='VyperResponse',
  full_name='iotex.VyperResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='compileOK', full_name='iotex.VyperResponse.compileOK', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verifyOK', full_name='iotex.VyperResponse.verifyOK', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='iotex.VyperResponse.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=190,
)


_VYPERSOURCE = _descriptor.Descriptor(
  name='VyperSource',
  full_name='iotex.VyperSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='iotex.VyperSource.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='iotex.VyperSource.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=236,
)

_VYPERREQUEST.fields_by_name['source'].message_type = _VYPERSOURCE
DESCRIPTOR.message_types_by_name['VyperRequest'] = _VYPERREQUEST
DESCRIPTOR.message_types_by_name['VyperResponse'] = _VYPERRESPONSE
DESCRIPTOR.message_types_by_name['VyperSource'] = _VYPERSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VyperRequest = _reflection.GeneratedProtocolMessageType('VyperRequest', (_message.Message,), {
  'DESCRIPTOR' : _VYPERREQUEST,
  '__module__' : 'proto.vyper_pb2'
  # @@protoc_insertion_point(class_scope:iotex.VyperRequest)
  })
_sym_db.RegisterMessage(VyperRequest)

VyperResponse = _reflection.GeneratedProtocolMessageType('VyperResponse', (_message.Message,), {
  'DESCRIPTOR' : _VYPERRESPONSE,
  '__module__' : 'proto.vyper_pb2'
  # @@protoc_insertion_point(class_scope:iotex.VyperResponse)
  })
_sym_db.RegisterMessage(VyperResponse)

VyperSource = _reflection.GeneratedProtocolMessageType('VyperSource', (_message.Message,), {
  'DESCRIPTOR' : _VYPERSOURCE,
  '__module__' : 'proto.vyper_pb2'
  # @@protoc_insertion_point(class_scope:iotex.VyperSource)
  })
_sym_db.RegisterMessage(VyperSource)


DESCRIPTOR._options = None

_VYPER = _descriptor.ServiceDescriptor(
  name='Vyper',
  full_name='iotex.Vyper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=238,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='compiler',
    full_name='iotex.Vyper.compiler',
    index=0,
    containing_service=None,
    input_type=_VYPERREQUEST,
    output_type=_VYPERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VYPER)

DESCRIPTOR.services_by_name['Vyper'] = _VYPER

# @@protoc_insertion_point(module_scope)
